import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import {createApp} from '../server/index.mjs';
import {passwordHash,plusDays,today} from '../server/core.mjs';
import {createPayments} from '../server/payments.mjs';
function fixture(t){const dir=mkdtempSync(path.join(os.tmpdir(),'hb-test-'));const sessions=new Map(),intents=new Map(),charges=new Map(),refunds=new Map(),keys=new Map();let creates=0,failBefore=false,loseAfter=false,refundState='pending';const messages=[];const fake={accounts:{retrieve:async()=>({charges_enabled:true,details_submitted:true})},checkout:{sessions:{create:async(p,o)=>{if(failBefore){failBefore=false;throw Error('network before');}let s=keys.get(o.idempotencyKey);if(!s){creates++;s={id:'cs_'+creates,url:'https://checkout.stripe.com/c/pay/test'+creates,status:'open',payment_status:'unpaid',amount_total:p.line_items.reduce((n,i)=>n+i.price_data.unit_amount,0),currency:'eur',metadata:p.metadata,payment_intent:'pi_'+creates};keys.set(o.idempotencyKey,s);sessions.set(s.id,s);intents.set(s.payment_intent,{id:s.payment_intent,metadata:p.payment_intent_data.metadata,latest_charge:null});}if(loseAfter){loseAfter=false;throw Error('response lost');}return s;},retrieve:async id=>structuredClone(sessions.get(id)),expire:async id=>{sessions.get(id).status='expired';return structuredClone(sessions.get(id));},list:async()=>({data:[...sessions.values()],has_more:false})}},paymentIntents:{retrieve:async id=>structuredClone(intents.get(id))},charges:{retrieve:async id=>structuredClone(charges.get(id))},refunds:{create:async(p,o)=>{let r=keys.get(o.idempotencyKey);if(!r){r={id:'re_'+refunds.size,status:refundState,amount:29800,payment_intent:p.payment_intent,metadata:p.metadata};keys.set(o.idempotencyKey,r);refunds.set(r.id,r);}return structuredClone(r);},retrieve:async id=>structuredClone(refunds.get(id))},webhooks:{constructEvent:(raw,sig)=>{if(sig!=='testsig')throw Error('signature');return JSON.parse(raw);}}};const app=createApp({directory:dir,origin:'http://localhost',bootstrapHash:passwordHash('initial-password-12345'),stripeFactory:()=>fake,transportFactory:()=>({verify:async()=>true,sendMail:async m=>messages.push(m)}),startWorkers:false});const store=app.store;store.set('stripe_key','sk_test_fake');const pay=createPayments({store,stripe:()=>fake,origin:'http://localhost',confirmationText:b=>'contract '+b.reference});const request=()=>store.createRequest({name:'Test Paar',email:'test@example.invalid',date:plusDays(today(),40),location:'Testlocation, Rendsburg',delivery:'delivery',customerType:'private'});const setup=()=>{const b=request();store.quote(b.id,30,25000);return store.startCheckout(b.id);};const paid=s=>{s.status='complete';s.payment_status='paid';const c={id:'ch_'+s.id,amount:29800,amount_refunded:0,refunded:false,payment_intent:s.payment_intent};charges.set(c.id,c);intents.get(s.payment_intent).latest_charge=c;return c;};t.after(()=>{app.close();rmSync(dir,{recursive:true,force:true});});return {app,store,pay,setup,request,paid,sessions,intents,charges,refunds,messages,get creates(){return creates;},failBefore(){failBefore=true;},loseAfter(){loseAfter=true;}};}
test('concurrent checkout and a lost provider response create only one payable session',async t=>{const f=fixture(t),b=f.setup();f.loseAfter();await assert.rejects(f.pay.createCheckout(b));assert.equal(f.store.booking(b.id).session_id,null);const [a,c]=await Promise.all([f.pay.createCheckout(b),f.pay.createCheckout(b)]);assert.equal(a.id,c.id);assert.equal(f.creates,1);assert.equal(f.store.booking(b.id).session_id,a.id);});
test('failure before provider creation recovers and overdue session expires before release',async t=>{const f=fixture(t),b=f.setup();f.failBefore();await assert.rejects(f.pay.createCheckout(b));f.store.db.prepare('UPDATE bookings SET checkout_expires=? WHERE id=?').run(Math.floor(Date.now()/1000)-10,b.id);await f.pay.reconcile();assert.equal(f.store.booking(b.id).status,'quoted');assert.equal(f.creates,1);assert.equal([...f.sessions.values()][0].status,'expired');});
test('full refund before completion never sends a booking confirmation',async t=>{const f=fixture(t),b=f.setup(),s=await f.pay.createCheckout(b),c=f.paid(s);c.refunded=true;c.amount_refunded=29800;f.charges.set(c.id,c);await f.pay.handleEvent({type:'charge.refunded',data:{object:{id:c.id}}});assert.equal(f.store.booking(b.id).status,'cancelled');await f.pay.applySession(s);assert.equal(f.store.booking(b.id).status,'cancelled');assert.equal(f.store.db.prepare("SELECT count(*) n FROM outbox WHERE id LIKE 'confirmation-%'").get().n,0);});
test('pending refunds recover; later failure remains cancelled and alerts owner',async t=>{const f=fixture(t),b=f.setup(),s=await f.pay.createCheckout(b);f.paid(s);await f.pay.applySession(s);assert.equal(f.store.booking(b.id).status,'confirmed');const r=await f.pay.refund(f.store.booking(b.id));assert.equal(f.store.booking(b.id).refund_status,'pending');f.refunds.get(r.id).status='succeeded';await f.pay.reconcile();assert.equal(f.store.booking(b.id).refund_status,'succeeded');f.refunds.get(r.id).status='failed';await f.pay.handleEvent({type:'refund.failed',data:{object:{id:r.id}}});assert.equal(f.store.booking(b.id).status,'cancelled');assert.equal(f.store.booking(b.id).refund_status,'failed');assert.ok(f.store.db.prepare('SELECT * FROM outbox WHERE id=?').get('refund-failed-'+r.id));});
test('old attempt refund cannot cancel a newer confirmed booking',async t=>{const f=fixture(t),b=f.setup(),s=await f.pay.createCheckout(b);const pi=f.intents.get(s.payment_intent);f.store.db.prepare("UPDATE bookings SET status='confirmed',payment_intent='pi_new' WHERE id=?").run(b.id);const c=f.paid(s);c.refunded=true;c.amount_refunded=29800;f.charges.set(c.id,c);await f.pay.handleEvent({type:'charge.refunded',data:{object:{id:c.id}}});assert.equal(f.store.booking(b.id).status,'confirmed');assert.equal(f.store.booking(b.id).payment_intent,'pi_new');});
test('incorrect payment amount makes no changes even if charge refunded',async t=>{const f=fixture(t),b=f.setup(),s=await f.pay.createCheckout(b);const before=f.store.booking(b.id);const c=f.paid(s);c.refunded=true;s.amount_total=1;await assert.rejects(f.pay.applySession(s),/Zahlungsbetrag/);assert.deepEqual(f.store.booking(b.id),before);});
test('old orphan raises owner review and explicit provider search safely resolves it',async t=>{const f=fixture(t),b=f.setup();f.store.db.prepare('UPDATE bookings SET checkout_expires=? WHERE id=?').run(Math.floor(Date.now()/1000)-23*3600,b.id);await f.pay.reconcile();assert.ok(f.store.booking(b.id).review_reason);assert.equal(f.creates,0);await f.pay.recover(b.id);assert.equal(f.store.booking(b.id).status,'expired');});
test('HTTP auth, CSRF, SMTP reset, gated payments and actual contract attachment',async t=>{const f=fixture(t);const server=http.createServer(f.app.handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());const base='http://127.0.0.1:'+server.address().port;let cookie='',csrf='';const call=async(route,body,extra={})=>{const r=await fetch(base+'/api/'+route,{method:body?'POST':'GET',headers:{Origin:'http://localhost',cookie,'Content-Type':'application/json','X-CSRF-Token':csrf,...extra},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')};};assert.equal((await call('config')).body.paymentsEnabled,false);assert.equal((await call('admin/state')).status,401);const login=await call('admin/login',{password:'initial-password-12345'});assert.equal(login.status,200);cookie=login.cookie.split(';')[0];csrf=login.body.csrf;assert.equal((await call('admin/block',{unit:1,start:plusDays(today(),100),end:plusDays(today(),101)},{'X-CSRF-Token':'bad'})).status,403);f.store.set('mail_test_sent',true);f.store.set('mail_received',true);assert.equal((await call('admin/settings',{smtpHost:'smtp.example.invalid',smtpUser:'sender@example.invalid',smtpPassword:'private-test'})).status,200);assert.equal(f.store.get('mail_test_sent'),false);assert.equal(f.store.get('mail_received'),false);assert.equal((await call('admin/activate',{live:true})).status,400);const b=f.setup(),s=await f.pay.createCheckout(b);f.paid(s);f.store.set('webhook_secret','whsec_fake');assert.equal((await call('stripe/webhook',{id:'evt_1',type:'checkout.session.completed',data:{object:{id:s.id}}},{'stripe-signature':'testsig'})).status,200);await f.app.flushMail();const contract=f.store.db.prepare("SELECT * FROM outbox WHERE id=?").get('confirmation-'+b.id);assert.ok(contract.attachment.includes('Widerrufsbelehrung'));assert.ok(contract.attachment.includes('Buchungsbedingungen'));assert.equal((await call('admin/password',{password:' spaces-are-valid-123 '})).status,200);assert.equal((await call('admin/login',{password:' spaces-are-valid-123 '})).status,200);});
