import { backupBeforeMigration, inventoryIssues, extensionDays, PRICE_VERSION } from './inventory.mjs';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes, createHash, timingSafeEqual, scryptSync, createCipheriv, createDecipheriv } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
export const hash = s => createHash('sha256').update(s).digest('hex');
export const token = () => randomBytes(24).toString('base64url');
export const passwordHash = password => { const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(password,salt,32).toString('hex'); };
export const passwordMatches = (password, saved) => { try {const [salt,key]=saved.split(':');return timingSafeEqual(Buffer.from(key,'hex'),scryptSync(password,salt,32));}catch{return false;} };
export function validDate(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const d=new Date(value+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===value;}
export const plusDays = (date,n) => new Date(Date.parse(date+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
export const today = (milliseconds=Date.now()) => new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(milliseconds));
export function priceFor(baseCents,distanceKm,delivery,extraDays=0,extraCents=4900){extensionDays(extraDays);if(!Number.isSafeInteger(extraCents)||extraCents<0)throw Error('Ungültiger Verlängerungspreis.');if(!Number.isInteger(baseCents)||baseCents<10000)throw Error('Ungültiger Grundpreis.');if(!Number.isFinite(distanceKm)||distanceKm<0||distanceKm>1000)throw Error('Ungültige Entfernung.');const travelCents=delivery==='pickup'?0:Math.max(0,Math.ceil(distanceKm/5)*5-10)*240;return {baseCents,travelCents,extensionCents:extraDays*extraCents,totalCents:baseCents+travelCents+extraDays*extraCents};}
export function createStore(directory,{now=()=>Date.now(),bootstrapHash='',legacyBaseCents=25000}={}){
 mkdirSync(directory,{recursive:true,mode:0o700});
 const keyPath=path.join(directory,'master.key');if(!existsSync(keyPath))writeFileSync(keyPath,randomBytes(32),{mode:0o600,flag:'wx'});
 const key=readFileSync(keyPath);const db=new DatabaseSync(path.join(directory,'bookings.sqlite'),{timeout:5000});
 const migrationBackup=backupBeforeMigration(db,directory,keyPath);
 db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL); CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,csrf TEXT NOT NULL,expires INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS bookings(id TEXT PRIMARY KEY,reference TEXT UNIQUE NOT NULL,token_hash TEXT UNIQUE NOT NULL,request_key TEXT,request_fingerprint TEXT,name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT NOT NULL,event_date TEXT NOT NULL,end_date TEXT NOT NULL,location TEXT NOT NULL,delivery TEXT NOT NULL,customer_type TEXT NOT NULL,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'requested',unit INTEGER,distance REAL,billed_distance REAL,base_cents INTEGER,travel_cents INTEGER,total_cents INTEGER,quote_until INTEGER,session_id TEXT UNIQUE,checkout_expires INTEGER,payment_intent TEXT,refund_id TEXT,refund_status TEXT,review_reason TEXT,created INTEGER NOT NULL,confirmed INTEGER,terms_version TEXT); CREATE TABLE IF NOT EXISTS blocks(id TEXT PRIMARY KEY,unit INTEGER NOT NULL CHECK(unit IN (1,2)),start_date TEXT NOT NULL,end_date TEXT NOT NULL,note TEXT NOT NULL); CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,created INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS withdrawals(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL,contract TEXT NOT NULL,message TEXT NOT NULL,created INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'received'); CREATE TABLE IF NOT EXISTS outbox(id TEXT PRIMARY KEY,to_address TEXT NOT NULL,subject TEXT NOT NULL,body TEXT NOT NULL,attachment TEXT,attempts INTEGER NOT NULL DEFAULT 0,next_attempt INTEGER NOT NULL,sent INTEGER,last_error TEXT);`);
 const columns = db.prepare('PRAGMA table_info(bookings)').all().map(c=>c.name);
 for(const column of ['refund_id','refund_status','review_reason'])if(!columns.includes(column))db.exec(`ALTER TABLE bookings ADD COLUMN ${column} TEXT`);
 if(!columns.includes('billed_distance'))db.exec('ALTER TABLE bookings ADD COLUMN billed_distance REAL');
 for(const column of ['request_key','request_fingerprint'])if(!columns.includes(column))db.exec(`ALTER TABLE bookings ADD COLUMN ${column} TEXT`);
 db.exec('CREATE UNIQUE INDEX IF NOT EXISTS bookings_request_key ON bookings(request_key)');
 for(const [column,type] of [['extension_days','INTEGER NOT NULL DEFAULT 0'],['extension_cents','INTEGER NOT NULL DEFAULT 0'],['pricing_version','TEXT'],['confirmation_method','TEXT']])if(!columns.includes(column))db.exec(`ALTER TABLE bookings ADD COLUMN ${column} ${type}`);
 const mailColumns=db.prepare('PRAGMA table_info(outbox)').all().map(c=>c.name);
 if(!mailColumns.includes('pdf_payload'))db.exec('ALTER TABLE outbox ADD COLUMN pdf_payload TEXT');
 db.exec(`CREATE TABLE IF NOT EXISTS email_offers(id TEXT PRIMARY KEY,booking_id TEXT NOT NULL REFERENCES bookings(id),snapshot TEXT NOT NULL,created INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'draft'); CREATE INDEX IF NOT EXISTS email_offers_booking ON email_offers(booking_id,created);`);
 const encrypt=value=>{const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',key,iv);const encrypted=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return [iv,cipher.getAuthTag(),encrypted].map(x=>x.toString('base64')).join('.');};
 const decrypt=value=>{const [iv,tag,data]=value.split('.').map(x=>Buffer.from(x,'base64'));const d=createDecipheriv('aes-256-gcm',key,iv);d.setAuthTag(tag);return JSON.parse(Buffer.concat([d.update(data),d.final()]).toString());};
 const set=(k,v)=>db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,encrypt(v));
 const get=(k,fallback=null)=>{const r=db.prepare('SELECT value FROM settings WHERE key=?').get(k);return r?decrypt(r.value):fallback;};
 if(!get('admin_hash')&&bootstrapHash)set('admin_hash',bootstrapHash);
 const transaction=fn=>{db.exec('BEGIN IMMEDIATE');try{const value=fn();db.exec('COMMIT');return value;}catch(e){db.exec('ROLLBACK');throw e;}};
 if(db.prepare('PRAGMA user_version').get().user_version<1)transaction(()=>{
  // Freeze the known historical request price; never rewrite an existing offer snapshot.
  db.prepare("UPDATE bookings SET base_cents=?,travel_cents=CASE WHEN delivery='pickup' THEN 0 ELSE travel_cents END,total_cents=CASE WHEN delivery='pickup' THEN ? ELSE total_cents END WHERE base_cents IS NULL").run(legacyBaseCents,legacyBaseCents);
  if(migrationBackup)set('one_box_backup',migrationBackup);
  set('physical_units',1);db.exec('PRAGMA user_version=1');
 });
 const enqueue=(to,subject,body,attachment=null,id=token(),pdfPayload=null)=>db.prepare('INSERT OR IGNORE INTO outbox(id,to_address,subject,body,attachment,next_attempt,pdf_payload) VALUES(?,?,?,?,?,?,?)').run(id,to,subject,body,attachment,now(),pdfPayload?JSON.stringify(pdfPayload):null);
 // Every historical assignment occupies the same physical box. Keep legacy unit=2 rows intact.
 const available=(start,end,exclude='')=>!db.prepare(`SELECT id FROM bookings WHERE id!=? AND status IN ('quoted','checkout','processing','confirmed','payment_review','refund_pending') AND event_date<? AND end_date>? LIMIT 1`).get(exclude,end,start)&&!db.prepare('SELECT id FROM blocks WHERE start_date<? AND end_date>? LIMIT 1').get(end,start)?[1]:[];
 const conflicts=()=>inventoryIssues(db,today(now()));
 const booking=id=>db.prepare('SELECT * FROM bookings WHERE id=?').get(id);
 const byToken=t=>db.prepare('SELECT * FROM bookings WHERE token_hash=?').get(hash(t));
 const createRequest=data=>{const id=token(),access=token(),reference='HB-'+randomBytes(5).toString('hex').toUpperCase(),extra=extensionDays(data.extensionDays??0),base=data.baseCents??(data.delivery==='pickup'?19900:24900),p=priceFor(base,0,data.delivery,extra,data.extensionCents??4900);db.prepare(`INSERT INTO bookings(id,reference,token_hash,name,email,phone,event_date,end_date,location,delivery,customer_type,message,created,request_key,request_fingerprint,base_cents,travel_cents,total_cents,extension_days,extension_cents,pricing_version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,reference,hash(access),data.name,data.email,data.phone||'',data.date,plusDays(data.date,2+extra),data.location,data.delivery,data.customerType,data.message||'',now(),data.requestKey||null,data.requestFingerprint||null,base,data.delivery==='pickup'?0:null,data.delivery==='pickup'?p.totalCents:null,extra,p.extensionCents,PRICE_VERSION);set('booking_access_'+id,access);return booking(id);};
 const quote=(id,distance,baseCents,options={})=>transaction(()=>{const b=booking(id);if(!b||!['requested','expired'].includes(b.status))throw Error('Diese Anfrage kann aktuell nicht angeboten werden.');if(b.event_date<plusDays(today(now()),15))throw Error('Onlinezahlungen benötigen mindestens 15 Tage Vorlauf; kurzfristige Termine bitte persönlich abstimmen.');const extra=extensionDays(options.extensionDays??0),end=plusDays(b.event_date,2+extra);if(b.delivery==='pickup'&&options.pickupChecked!==true)throw Error('Bitte sicheren Transport und Bedienbarkeit bei Selbstabholung prüfen.');if(!available(b.event_date,end,id).length)throw Error('Für diesen Zeitraum einschließlich Rückgabe ist die Fotobox belegt.');const p=priceFor(baseCents,distance,b.delivery,extra,options.extensionCents??4900);db.prepare(`UPDATE bookings SET status='quoted',unit=1,distance=?,billed_distance=?,base_cents=?,travel_cents=?,total_cents=?,extension_days=?,extension_cents=?,end_date=?,pricing_version=?,quote_until=?,session_id=NULL,payment_intent=NULL,terms_version=? WHERE id=?`).run(distance,Math.ceil(distance/5)*5,p.baseCents,p.travelCents,p.totalCents,extra,p.extensionCents,end,PRICE_VERSION,now()+48*3600000,PRICE_VERSION,id);return booking(id);});
 const startCheckout=id=>transaction(()=>{const b=booking(id);if(!b||b.status!=='quoted'||b.quote_until<=now())throw Error('Dieses Angebot ist nicht mehr zur Zahlung verfügbar.');if(b.event_date<plusDays(today(now()),15))throw Error('Onlinezahlungen benötigen mindestens 15 Tage Vorlauf. Bitte meldet euch persönlich.');if(![1,2].includes(b.unit)||!available(b.event_date,b.end_date,b.id).length)throw Error('Der Termin muss erneut geprüft werden.');db.prepare("UPDATE bookings SET status='checkout',checkout_expires=?,terms_version=COALESCE(terms_version,'2026-09-05-v1') WHERE id=?").run(Math.floor(now()/1000)+31*60,id);return booking(id);});
 const addBlock=(unit,start,end,note)=>transaction(()=>{if(unit!==1||!validDate(start)||!validDate(end)||end<=start)throw Error('Ungültiger Zeitraum.');if(!available(start,end).includes(unit))throw Error('Die Box ist in diesem Zeitraum bereits reserviert.');const id=token();db.prepare('INSERT INTO blocks VALUES(?,?,?,?,?)').run(id,unit,start,end,note);return id;});
 const applySession=(s,{confirmationText})=>transaction(()=>{const b=booking(s.metadata?.booking_id);if(!b||b.session_id!==s.id)return false;if(s.currency!=='eur'||s.amount_total!==b.total_cents)throw Error('Zahlungsbetrag stimmt nicht überein.');if(s.payment_status==='paid'){
  if(['confirmed','refunded','cancelled','refund_pending','refund_failed'].includes(b.status))return true;
  const reserved=['checkout','processing','quoted'].includes(b.status)&&[1,2].includes(b.unit)&&available(b.event_date,b.end_date,b.id).length>0;
  const state=reserved?'confirmed':'payment_review';db.prepare('UPDATE bookings SET status=?,payment_intent=?,confirmed=? WHERE id=?').run(state,typeof s.payment_intent==='string'?s.payment_intent:s.payment_intent?.id||null,now(),b.id);
  if(reserved){const fresh=booking(b.id);enqueue(b.email,'Eure Fotobox Rendsburg-Buchung '+b.reference,confirmationText(fresh),confirmationText(fresh),'confirmation-'+b.id,{kind:'confirmation',booking:fresh});}else enqueue(get('owner_email','uhighcauseidope@gmail.com'),'Fotobox Rendsburg: Zahlung bitte prüfen',`Buchung ${b.reference}: Zahlung eingegangen, Termin nicht automatisch bestätigt. Bitte zeitnah prüfen.`);
 }else if(s.status==='complete'){if(['checkout','quoted','processing'].includes(b.status))db.prepare("UPDATE bookings SET status='processing' WHERE id=?").run(b.id);
 }else if(s.status==='expired'&&['checkout','quoted'].includes(b.status)){db.prepare('UPDATE bookings SET status=?,session_id=NULL WHERE id=?').run(b.quote_until>now()?'quoted':'expired',b.id);}
 return true;});
 return {db,now,set,get,transaction,enqueue,available,conflicts,booking,byToken,createRequest,quote,startCheckout,addBlock,applySession,close:()=>db.close()};
}
