import http from 'node:http';
import {createPayments} from './payments.mjs';
import {calendarRange,calendarData} from './calendar.mjs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { readFileSync } from 'node:fs';
import Stripe from 'stripe';
import nodemailer from 'nodemailer';
import {createStore,hash,token,passwordMatches,passwordHash,validDate,plusDays,today} from './core.mjs';
export function createApp({directory=process.env.DATA_DIR||'./data',origin=process.env.SITE_URL||'http://localhost:4173',baseCents=Number(process.env.BASE_PRICE_CENTS||25000),bootstrapHash=process.env.ADMIN_PASSWORD_HASH||'',stripeFactory=key=>new Stripe(key,{maxNetworkRetries:2,timeout:20000}),transportFactory=opts=>nodemailer.createTransport(opts),startWorkers=true}={}){
 const store=createStore(directory,{bootstrapHash});const {db,get,set,enqueue}=store;
 const owner=()=>get('owner_email','uhighcauseidope@gmail.com');
 const legal=version=>readFileSync(new URL(version==='2026-09-05-v1'?'./terms-v1.txt':'./terms.txt',import.meta.url),'utf8')+'\n\n'+readFileSync(new URL('./withdrawal.txt',import.meta.url),'utf8');
 const euro=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n/100);
 const when=n=>new Intl.DateTimeFormat('de-DE',{timeZone:'Europe/Berlin',dateStyle:'long',timeStyle:'long'}).format(new Date(n));
 const stripe=()=>{const key=get('stripe_key');if(!key)throw Error('Zahlungsanbieter noch nicht verbunden.');return stripeFactory(key);};
 const transport=()=>{const c=get('smtp');if(!c?.host||!c?.user||!c?.pass)throw Error('Bestätigungsmails noch nicht eingerichtet.');return transportFactory({host:c.host,port:c.port||465,secure:(c.port||465)===465,auth:{user:c.user,pass:c.pass},connectionTimeout:12000,greetingTimeout:12000,socketTimeout:20000});};
 const readiness=()=>({payments:!!get('stripe_live_ready'),email:!!get('mail_received'),calendar:!!get('calendar_reviewed'),conditions:!!get('terms_reviewed'),webhook:!!get('webhook_secret')&&!!get('webhook_verified'),live:!!get('live')});
 const ready=()=>{const r=readiness();return r.live&&r.payments&&r.email&&r.calendar&&r.conditions&&r.webhook;};
 const mailReady=()=>!!get('mail_received');
 const travelBasis=b=>b.delivery==='pickup'?'Selbstabholung ohne Fahrtkosten.':b.billed_distance==null?`Vereinbarte einfache Straßenentfernung: ${b.distance} km.`:`Einfache Straßenentfernung: ${b.distance} km; auf ${b.billed_distance} km aufgerundet. Davon 10 km frei, vier Fahrstrecken zu je 0,60 € pro zusätzlichem Kilometer.`;
 const confirmationText=b=>`Fotobox Rendsburg – Buchungsbestätigung ${b.reference}\n\nHallo ${b.name},\n\neure Zahlung ist eingegangen. Eure Fotobox ist verbindlich gebucht.\nVeranstaltung: ${b.event_date}\nEine digitale Fotobox für bis zu 24 Stunden.\nOrt: ${b.location}\nÜbergabe: ${b.delivery==='pickup'?'Selbstabholung in Rendsburg':'Lieferung, Aufbau, Einweisung und Abholung'}\nMietpreis: ${euro(b.base_cents)}\nFahrtkosten: ${euro(b.travel_cents)}\n${travelBasis(b)}\nGesamtbetrag: ${euro(b.total_cents)}\nDie Leistungen sind gemäß § 19 UStG umsatzsteuerfrei.\n\nUhrzeiten der Übergabe stimmen wir persönlich ab. Kamera mit Livebild und Fernauslöser; digitale Fotos werden nach der Veranstaltung manuell in euren eigenen Google-Drive-Ordner übertragen. Keine Sofortausdrucke. Die gebuchte Leistung umfasst eine Fotobox, keine dauerhafte Betreuung während der Veranstaltung.\n\nVertragspartner: Finn Ole Bierlich, Fotobox Rendsburg, Wallstraße 34, 24768 Rendsburg. Telefon 0171 28 07 197, E-Mail ${owner()}.\n\n${legal(b.terms_version||'2026-09-05-v1')}`;
 let mailBusy=false;
 async function flushMail(){if(mailBusy)return;mailBusy=true;try{let tx;try{tx=transport();}catch{return;}const jobs=db.prepare('SELECT * FROM outbox WHERE sent IS NULL AND next_attempt<=? ORDER BY next_attempt LIMIT 10').all(Date.now());for(const j of jobs){try{await tx.sendMail({from:{name:'Fotobox Rendsburg',address:get('smtp').user},to:j.to_address,replyTo:owner(),subject:j.subject,text:j.body,attachments:j.attachment?[{filename:'Fotobox-Rendsburg-Vertragsinformationen.txt',content:j.attachment,contentType:'text/plain; charset=utf-8'}]:[]});db.prepare('UPDATE outbox SET sent=?,last_error=NULL WHERE id=?').run(Date.now(),j.id);}catch{db.prepare('UPDATE outbox SET attempts=attempts+1,next_attempt=?,last_error=? WHERE id=?').run(Date.now()+Math.min(3600000,60000*2**Math.min(j.attempts,6)),'Versand fehlgeschlagen – SMTP prüfen.',j.id);}}}finally{mailBusy=false;}}
 const payments=createPayments({store,stripe,origin,confirmationText});
 let reconcileBusy=false;
 async function reconcile(){if(reconcileBusy)return;reconcileBusy=true;try{await payments.reconcile();}finally{reconcileBusy=false;}}
 const limits=new Map();
 function rate(ip,group,max,windowMs){const key=group+':'+ip;const now=Date.now();let r=limits.get(key);if(!r||r.until<now)r={count:0,until:now+windowMs};r.count++;limits.set(key,r);if(limits.size>10000)for(const [k,v] of limits)if(v.until<now)limits.delete(k);if(r.count>max)throw Object.assign(Error('Bitte wartet einen Moment und versucht es erneut.'),{status:429});}
 const clean=(v,max=300)=>typeof v==='string'?v.trim().slice(0,max):'';
 const email=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)&&v.length<=200&&!/[\r\n]/.test(v);
 const quoteURL=b=>`${origin}/buchen/?angebot=${get('booking_access_'+b.id)}`;
 const sessionFor=req=>{const m=(req.headers.cookie||'').match(/(?:^|;\s*)hb_admin=([^;]+)/);return m?db.prepare('SELECT * FROM sessions WHERE id=? AND expires>?').get(hash(m[1]),Date.now()):null;};
 function publicBooking(b){return {reference:b.reference,name:b.name,eventDate:b.event_date,location:b.location,delivery:b.delivery,status:b.status,baseCents:b.base_cents,travelCents:b.travel_cents,totalCents:b.total_cents,refundStatus:b.refund_status,distanceKm:b.distance,billedDistanceKm:b.billed_distance,termsVersion:b.terms_version||'2026-09-05-v1',quoteUntil:b.quote_until,canPay:ready()&&((b.status==='quoted'&&b.quote_until>Date.now()&&b.event_date>=plusDays(today(),15))||b.status==='checkout'),paymentPending:['checkout','processing'].includes(b.status)};}
 async function handler(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');const send=(status,obj)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(obj));};
 try{const url=new URL(req.url,origin),route=url.pathname,method=req.method;const ip=req.headers['x-real-ip']||req.socket.remoteAddress;rate(ip,'all',240,60000);
 if(method==='GET'&&route==='/api/health')return send(200,{ok:true});
 if(method==='GET'&&route==='/api/config')return send(200,{brand:'Fotobox Rendsburg',baseCents,requestEnabled:true,serverToday:today(),maxDate:plusDays(today(),540),paymentsEnabled:ready(),klarnaEnabled:ready()&&!!get('klarna_approved'),calendarReviewed:!!get('calendar_reviewed'),quoteRequired:true,units:2,minOnlineDate:plusDays(today(),15)});
 if(method==='GET'&&route==='/api/availability'){const range=calendarRange(url.searchParams);await reconcile();return send(200,calendarData(store,range));}
 let raw=Buffer.alloc(0),body={};if(method==='POST'||method==='DELETE'){for await(const chunk of req){raw=Buffer.concat([raw,chunk]);if(raw.length>65536)throw Object.assign(Error('Anfrage zu groß.'),{status:413});}if(route!=='/api/stripe/webhook'){if(req.headers.origin!==origin)throw Object.assign(Error('Diese Anfrage ist nicht zulässig.'),{status:403});try{body=raw.length?JSON.parse(raw.toString()):{};}catch{throw Error('Ungültige Anfrage.');}}}
 if(route==='/api/admin/login'&&method==='POST'){rate(ip,'login',6,15*60000);if(typeof body.password!=='string'||body.password.length>200||!passwordMatches(body.password,get('admin_hash','')))return send(401,{error:'Anmeldung fehlgeschlagen.'});const secret=token(),csrf=token();db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(secret),csrf,Date.now()+8*3600000);res.setHeader('Set-Cookie',`hb_admin=${secret}; HttpOnly; SameSite=Strict; Path=/api/admin; Max-Age=28800${origin.startsWith('https:')?'; Secure':''}`);return send(200,{csrf});}
 if(route.startsWith('/api/admin/')){const session=sessionFor(req);if(!session)return send(401,{error:'Bitte anmelden.'});if(method!=='GET'&&req.headers['x-csrf-token']!==session.csrf)return send(403,{error:'Sitzung bitte neu laden.'});
 if(method==='GET'&&route==='/api/admin/state')return send(200,{csrf:session.csrf,readiness:readiness(),klarnaApproved:!!get('klarna_approved'),bookings:db.prepare('SELECT * FROM bookings ORDER BY created DESC LIMIT 300').all().map(({token_hash,...b})=>b),blocks:db.prepare('SELECT * FROM blocks ORDER BY start_date').all(),withdrawals:db.prepare('SELECT * FROM withdrawals ORDER BY created DESC LIMIT 100').all(),failedEmails:db.prepare('SELECT id,to_address,subject,attempts,last_error FROM outbox WHERE sent IS NULL LIMIT 100').all()});
 if(method==='GET'&&route==='/api/admin/calendar'){const range=calendarRange(url.searchParams,{owner:true});await reconcile();return send(200,calendarData(store,range,{owner:true}));}
 if(method==='POST'&&route==='/api/admin/calendar-review'){if(typeof body.reviewed!=='boolean')throw Error('Bitte den Kalenderstatus angeben.');set('calendar_reviewed',body.reviewed);return send(200,{ok:true,reviewed:body.reviewed});}
 if(method==='POST'&&route==='/api/admin/logout'){db.prepare('DELETE FROM sessions WHERE id=?').run(session.id);res.setHeader('Set-Cookie','hb_admin=; HttpOnly; SameSite=Strict; Path=/api/admin; Max-Age=0');return send(200,{ok:true});}
 if(method==='POST'&&route==='/api/admin/password'){if(typeof body.password!=='string'||body.password.length<16||body.password.length>200)throw Error('Bitte 16 bis 200 Zeichen verwenden.');set('admin_hash',passwordHash(body.password));db.exec('DELETE FROM sessions');return send(200,{ok:true});}
 if(method==='POST'&&route==='/api/admin/settings'){
  if(body.stripeKey){const key=clean(body.stripeKey,300);if(!/^(sk|rk)_(live|test)_/.test(key))throw Error('Bitte einen gültigen geheimen Stripe-Schlüssel hinterlegen.');const account=await stripeFactory(key).accounts.retrieve();set('stripe_key',key);set('stripe_live_ready',key.includes('_live_')&&account.charges_enabled===true&&account.details_submitted===true);set('live',false);}
  if(body.webhookSecret){if(!/^whsec_/.test(body.webhookSecret))throw Error('Ungültiges Webhook-Geheimnis.');set('webhook_secret',clean(body.webhookSecret,300));set('webhook_verified',false);set('live',false);}
  if(body.smtpHost){const host=clean(body.smtpHost,200);if(!/^[a-z0-9.-]+$/i.test(host)||host==='localhost'||/^\d/.test(host)||/\.(local|internal)$/i.test(host))throw Error('Bitte einen öffentlichen SMTP-Servernamen verwenden.');const config={host,port:Number(body.smtpPort)||465,user:clean(body.smtpUser,200),pass:clean(body.smtpPassword,500)};if(![465,587].includes(config.port)||!email(config.user)||!config.pass)throw Error('SMTP-Angaben unvollständig.');await transportFactory({host:config.host,port:config.port,secure:config.port===465,auth:{user:config.user,pass:config.pass},connectionTimeout:12000}).verify();set('smtp',config);set('mail_received',false);set('mail_test_sent',false);set('live',false);}
  return send(200,{ok:true,readiness:readiness()});
 }
 if(method==='POST'&&route==='/api/admin/test-mail'){const tx=transport();await tx.sendMail({from:{name:'Fotobox Rendsburg',address:get('smtp').user},to:owner(),subject:'Fotobox Rendsburg – Test der Buchungsbestätigung',text:'Wenn diese Nachricht bei dir angekommen ist, funktioniert der Versand über die hinterlegten E-Mail-Einstellungen. Du kannst den Empfang anschließend im Verwaltungsbereich bestätigen.'});set('mail_test_sent',true);return send(200,{ok:true});}
 if(method==='POST'&&route==='/api/admin/activate'){if(body.mailReceived&&!get('mail_test_sent'))throw Error('Bitte zuerst eine Testbestätigung versenden.');set('mail_received',body.mailReceived===true);set('calendar_reviewed',body.calendarReviewed===true);set('terms_reviewed',body.termsReviewed===true);set('klarna_approved',body.klarnaApproved===true);const r=readiness();if(body.live===true&&!(r.payments&&r.email&&r.calendar&&r.conditions&&r.webhook))throw Error('Vor Livezahlungen bitte alle erforderlichen Einrichtungen abschließen.');set('live',body.live===true);void flushMail();return send(200,{ok:true,readiness:readiness()});}
 if(method==='POST'&&route==='/api/admin/block'){const start=clean(body.start,10),end=clean(body.end,10);return send(200,{id:store.addBlock(Number(body.unit),start,end,clean(body.note,300))});}
 if(method==='POST'&&route==='/api/admin/unblock'){db.prepare('DELETE FROM blocks WHERE id=?').run(clean(body.id,100));return send(200,{ok:true});}
 if(method==='POST'&&route==='/api/admin/quote'){if(!ready())throw Error('Bitte zuerst Zahlungen, E-Mails, Kalender und Buchungsbedingungen einrichten.');if(store.booking(clean(body.id,100))?.delivery==='custom')throw Error('Den individuellen Umfang bitte persönlich abstimmen.');await reconcile();const b=store.quote(clean(body.id,100),Number(body.distanceKm),baseCents);enqueue(b.email,'Euer Fotobox Rendsburg-Angebot '+b.reference,`Hallo ${b.name},\n\neuer Termin ${b.event_date} ist für eine Fotobox vorgemerkt.\nOrt: ${b.location}\nMiete: ${euro(b.base_cents)}\nFahrtkosten: ${euro(b.travel_cents)}\n${travelBasis(b)}\nGesamt: ${euro(b.total_cents)}. Die Leistungen sind gemäß § 19 UStG umsatzsteuerfrei.\n\nIhr könnt dieses Angebot innerhalb von 48 Stunden online abschließen und bezahlen:\n${quoteURL(b)}\n\nDie Buchung wird nach erfolgreicher Zahlung bestätigt.\n\nFotobox Rendsburg · Finn Ole Bierlich · Wallstraße 34, 24768 Rendsburg · 0171 28 07 197`);void flushMail();return send(200,{ok:true,url:quoteURL(b)});}
 if(method==='POST'&&route==='/api/admin/release'){const b=store.booking(clean(body.id,100));if(!b||!['requested','quoted','expired'].includes(b.status)||b.session_id)throw Error('Eine laufende oder bezahlte Buchung kann hier nicht freigegeben werden.');db.prepare("UPDATE bookings SET status='cancelled' WHERE id=?").run(b.id);return send(200,{ok:true});}
 if(method==='POST'&&route==='/api/admin/refund'){const r=await payments.refund(store.booking(clean(body.id,100)));void flushMail();return send(200,{ok:true,status:r.status});}
 if(method==='POST'&&route==='/api/admin/recover')return send(200,await payments.recover(clean(body.id,100)));
 if(method==='POST'&&route==='/api/admin/withdrawal-done'){db.prepare("UPDATE withdrawals SET status='reviewed' WHERE id=?").run(clean(body.id,100));return send(200,{ok:true});}
 }
 if(route==='/api/request'&&method==='POST'){
  if(body.website)return send(200,{ok:true});
  const data={name:clean(body.name,120),email:clean(body.email,200),phone:clean(body.phone,50),date:clean(body.date,10),location:clean(body.location,500),delivery:['pickup','custom'].includes(body.delivery)?body.delivery:'delivery',customerType:body.customerType==='business'?'business':'private',message:clean(body.message,2000)};
  if(!data.name||!email(data.email)||!validDate(data.date)||data.date<today()||data.date>plusDays(today(),540)||data.location.length<5)throw Error('Bitte Namen, E-Mail, Veranstaltungsdatum und vollständige Location angeben.');
  const requestKey=body.requestId===undefined?token():clean(body.requestId,100);if(!/^[a-zA-Z0-9_-]{20,100}$/.test(requestKey))throw Error('Bitte die Anfrage erneut öffnen.');const fingerprint=hash(JSON.stringify(data));
  await reconcile();
  const b=store.transaction(()=>{
   const previous=db.prepare('SELECT * FROM bookings WHERE request_key=?').get(requestKey);if(previous){if(previous.request_fingerprint!==fingerprint)throw Object.assign(Error('Die Anfrage wurde mit anderen Angaben bereits übermittelt. Bitte einen neuen Vorgang beginnen.'),{status:409});return previous;}
   rate(ip,'request',5,3600000);
   if(get('calendar_reviewed')&&!store.available(data.date,plusDays(data.date,2)).length)throw Object.assign(Error('Dieser Termin ist inzwischen nicht mehr verfügbar. Bitte wählt einen anderen Tag.'),{status:409});
   const saved=store.createRequest({...data,requestKey,requestFingerprint:fingerprint});
   if(mailReady()){enqueue(data.email,'Eure Terminanfrage '+saved.reference,`Hallo ${saved.name},\n\neure Anfrage für ${saved.event_date} ist eingegangen. Wir prüfen Verfügbarkeit, Übergabe und Fahrtkosten. Diese Nachricht ist noch keine Buchungsbestätigung.\n\nReferenz: ${saved.reference}\nOrt: ${saved.location}\n\nFotobox Rendsburg · 0171 28 07 197`,null,'request-received-'+saved.id);enqueue(owner(),'Neue Fotobox Rendsburg-Anfrage '+saved.reference,`Neue Anfrage für ${saved.event_date}. Bitte im Verwaltungsbereich prüfen: ${origin}/verwaltung/`,null,'request-owner-'+saved.id);}
   return saved;
  });
  const emailQueued=!!db.prepare('SELECT id FROM outbox WHERE id=?').get('request-received-'+b.id);
  const receiptText=`Fotobox Rendsburg – Eingangsbestätigung eurer Terminanfrage\n\nReferenz: ${b.reference}\nEingegangen: ${when(b.created)}\nName: ${b.name}\nE-Mail: ${b.email}\nTelefon: ${b.phone||'Nicht angegeben'}\nDatum: ${b.event_date}\nLocation: ${b.location}\nÜbergabe: ${b.delivery==='pickup'?'Selbstabholung':b.delivery==='custom'?'Individuelle Anfrage':'Lieferung und Abholung'}\nNachricht: ${b.message||'Keine'}\n\nEure Anfrage wurde gespeichert. Sie ist unverbindlich und reserviert noch keine Fotobox. Wir prüfen Termin, Übergabe und Fahrtkosten und melden uns persönlich bei euch.\n\nFotobox Rendsburg · Finn Ole Bierlich · Wallstraße 34, 24768 Rendsburg\n0171 28 07 197 · uhighcauseidope@gmail.com`;
  if(emailQueued)void flushMail();return send(200,{ok:true,reference:b.reference,receiptText,emailQueued});
 }
 if(route==='/api/quote'&&method==='GET'){const b=store.byToken(clean(url.searchParams.get('token'),100));if(!b)return send(404,{error:'Angebot nicht gefunden.'});if(b.session_id&&['checkout','processing'].includes(b.status)){try{await payments.applySession(await stripe().checkout.sessions.retrieve(b.session_id));}catch{}}return send(200,{booking:publicBooking(store.booking(b.id)),klarna:ready()&&get('klarna_approved')===true&&b.customer_type==='private'});}
 if(route==='/api/checkout'&&method==='POST'){rate(ip,'checkout',8,3600000);if(!ready())throw Error('Onlinezahlung ist noch nicht freigeschaltet.');if(body.acceptTerms!==true)throw Error('Bitte Buchungsbedingungen und Widerrufsbelehrung bestätigen.');let b=store.byToken(clean(body.token,100));if(!b)throw Error('Angebot nicht gefunden.');if(b.status==='quoted')b=store.startCheckout(b.id);if(!['checkout','processing'].includes(b.status))throw Error('Die Zahlung ist aktuell nicht verfügbar. Bitte den Buchungsstatus aktualisieren.');const s=await payments.createCheckout(b);if(s.status!=='open')throw Error('Die Zahlung wird bearbeitet oder ist abgelaufen. Bitte den Buchungsstatus aktualisieren.');if(!s.url?.startsWith('https://checkout.stripe.com/'))throw Error('Ungültige Zahlungsadresse.');return send(200,{url:s.url});}
 if(route==='/api/withdraw'&&method==='POST'){rate(ip,'withdraw',5,3600000);const name=clean(body.name,150),address=clean(body.email,200),contract=clean(body.contract,500),message=clean(body.message,2000);if(!name||!email(address)||!contract||body.confirm!==true)throw Error('Bitte Namen, Vertragsangaben und E-Mail bestätigen.');const id=token(),created=Date.now();db.prepare('INSERT INTO withdrawals(id,name,email,contract,message,created) VALUES(?,?,?,?,?,?)').run(id,name,address,contract,message,created);const receipt=`Eingangsbestätigung eures Widerrufs\n\nName: ${name}\nVertrag/Vertragsteil: ${contract}\nErklärung: Hiermit widerrufe ich den angegebenen Vertrag beziehungsweise Vertragsteil.\nZusatz: ${message}\n\nEingegangen am ${when(created)}.\nVorgangsnummer: ${id}\n\nDies bestätigt den Eingang eurer Erklärung. Die Zuordnung und eine gegebenenfalls erforderliche Erstattung werden gesondert bearbeitet.\nFotobox Rendsburg · Finn Ole Bierlich · Wallstraße 34, 24768 Rendsburg · 0171 28 07 197`;enqueue(address,'Eingang eures Widerrufs',receipt);enqueue(owner(),'Neuer Widerruf bei Fotobox Rendsburg',`Ein Widerruf ist eingegangen. Bitte zeitnah prüfen: ${origin}/verwaltung/`);await flushMail();return send(200,{ok:true,receipt,emailQueued:true});}
 if(route==='/api/stripe/webhook'&&method==='POST'){const secret=get('webhook_secret');if(!secret)return send(503,{error:'Webhook noch nicht eingerichtet.'});let event;try{event=stripe().webhooks.constructEvent(raw,req.headers['stripe-signature'],secret);}catch{return send(400,{error:'Ungültige Signatur.'});}set('webhook_verified',true);if(db.prepare('SELECT id FROM events WHERE id=?').get(event.id))return send(200,{ok:true});await payments.handleEvent(event);db.prepare('INSERT OR IGNORE INTO events VALUES(?,?)').run(event.id,Date.now());void flushMail();return send(200,{ok:true});}
 return send(404,{error:'Nicht gefunden.'});
 }catch(e){if(!res.headersSent)send(e.status||(req.url==='/api/stripe/webhook'?500:400),{error:e.type?.startsWith('Stripe')?'Der Zahlungsanbieter konnte die Anfrage gerade nicht verarbeiten. Bitte erneut versuchen oder Kontakt aufnehmen.':String(e.message||'Anfrage fehlgeschlagen.').slice(0,250)});else res.end();}}
 const timers=startWorkers?[setInterval(()=>void flushMail(),30000),setInterval(()=>void reconcile(),60000)]:[];timers.forEach(t=>t.unref());
 return {handler,store,reconcile,flushMail,readiness,close(){timers.forEach(clearInterval);store.close();}};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const app=createApp();const server=http.createServer(app.handler);server.listen(Number(process.env.PORT||3000),'0.0.0.0',()=>console.log('Fotobox Rendsburg booking service ready.'));process.on('SIGTERM',()=>server.close(()=>{app.close();process.exit(0);}));}
